### ISSUE TITLE
Makefile not detected when filename is not capitalized

### ISSUE THREAD

**Issue by leggettc18** [carlos-algms/vscode-make-task-provider#6]
When I installed this extension, it would not detect my makefile because the file name was written lowercase, like "makefile". When I renamed it to "Makefile" with a capital M, it worked perfectly fine. I could still run make commands normally when it was lowercase, so I feel like this should be considered a bug (if make can run the makefile just fine then this extension should be able to as well). This might only be a problem on Linux (and WSL2) since Windows is typically case-insensitive..

**Comment by carlos-algms** [comment]
Hey @leggettc18, thanks for reporting the issue.

You are completely right, [here](https://github.com/carlos-algms/vscode-make-task-provider/blob/5d94d81331d71ad7cda29ccae6142a30ab5a757a/src/shared/constants.ts#L6) we have the name `Makefile` with a capital `M`, and it is used everywhere in the extension to match the file name.

Also, the [official Docs](https://www.gnu.org/software/make/manual/html_node/Makefile-Names.html) says that `make` is not case-sensitive related to the file name. 

I will investigate and check how VSCode will allow me to watch for files not case-sensitive.

**Comment by carlos-algms** [comment]
Also, I do not have a "custom" make parser, I use `make` cmd to check what is available to work with. 
The problem seems to be that the extension is not "activating" due to the capital M, and not trying to get the tasks to list.

**Comment by leggettc18** [comment]
Yeah I figured it just wasn't seeing the makefile at all due to the lack of capital M, given that it was working properly when I changed the filename to a capital M. Thanks for looking into it! Not a big deal all-in-all, just figured it was either easy to fix or if not it should be documented somewhere.

**Comment by carlos-algms** [comment]
Hey @leggettc18, I just released a new version `v1.15.0` and it will allow you to have case-**insensitive** file names for the default `Makefile` file name. 
please let me know if it works for you.

**Comment by leggettc18** [comment]
Hey, I'm not sure whether it would work or not, I renamed an existing one back to lowercase from uppercase and all the tasks are still there and there's probably a naming collision but I can't figure out how to get rid of the old tasks.

**Comment by leggettc18** [comment]
Or maybe there's a separate issue with the openFile command provided by the extension because the file that shows up in the makefile tasks section in the explorer can't be opened if I right click on it and it still shows the uppercase filename.

**Comment by leggettc18** [comment]
Ok, I edited the name of a make task in my lowercase-named makefile and it updated on the task list. So I think the detection of the file works but something's wrong with the openFile command.

**Comment by leggettc18** [comment]
If I may offer a suggestion, I've never coded a VSCode extension before but I noticed that in the src/shared/config.ts file it appears that it references a command called openMakefile for the VSCode openMakefile command but I cannot find an openMakefile command anywhere else in the extension's source code. I do see an openHostfile though, is there perhaps a desync in naming conventions going on here or am I just misunderstanding how vscode extensions work?

**Comment by carlos-algms** [comment]
@leggettc18 thanks for the debugging session. 
I will investigate the naming issue you just mentioned, but I'm pretty sure it will be fixed in the next release, as I'm creating a new option to allow you to define any name to your makefiles, as the documentation says, `Make` allows it. 

About the capital/lowercase, this one seems to be fixed as well in my current branch.

**Comment by leggettc18** [comment]
Ok. It's definitely fixed in terms of parsing the makefile and creating tasks whether the makefile is capitalized or not, so thanks for fixing that.

**Comment by carlos-algms** [comment]
Hey @leggettc18 I just released a new version `2.0.2`. 

It is now possible to customize any number of names for your `Makefiles` by adding the names to the config `make-task-provider.makefileNames`.

With this release, a "dynamic" file watcher will watch for any file change that matches the names you set and refresh the available tasks. 

This release should fix all the mentioned issues.

**Comment by leggettc18** [comment]
Can confirm, everything that didn't work before is now working! Thanks for seeing it through.

**Comment by carlos-algms** [comment]
Thank you very much @leggettc18 for spending your time debugging and testing the extension. 
That is the spirit that moves the open-source projects forward, and also, that is why VSCode and its extensions are so great.
